with open('design-system/themes/aqua/button.scss', 'rb') as f:
    raw = f.read()
text = raw.decode('utf-8')

old = (
    '.btn-icon {\r\n'
    '  width: 36px;\r\n'
    '  height: 36px;\r\n'
    '  border-radius: 8px; // rounded-rect, not circle \u2014 matches Aqua toolbar\r\n'
    '  background: transparent;\r\n'
    '  color: var(--color-gray-500, #888);\r\n'
    '  border: 1px solid transparent;\r\n'
    '  padding: 0;\r\n'
    '  display: flex;\r\n'
    '  justify-content: center;\r\n'
    '  align-items: center;\r\n'
    '  flex-shrink: 0;\r\n'
    '  cursor: pointer;\r\n'
    '  user-select: none;\r\n'
    '  transition:\r\n'
    '    background 0.12s,\r\n'
    '    border-color 0.12s,\r\n'
    '    box-shadow 0.12s,\r\n'
    '    color 0.12s;\r\n'
    '  box-shadow: none;\r\n'
    '\r\n'
    '  // Remove the Aqua gel shine \u2014 icon buttons are transparent\r\n'
    '  &::after {\r\n'
    '    display: none;\r\n'
    '  }\r\n'
    '\r\n'
    '  // Hover: subtle silver Aqua gel capsule (Tiger era toolbar item highlight)\r\n'
    '  &:hover {\r\n'
    '    background: linear-gradient(to bottom,\r\n'
    '        rgba(255, 255, 255, 0.82) 0%,\r\n'
    '        rgba(225, 225, 225, 0.65) 50%,\r\n'
    '        rgba(210, 210, 210, 0.60) 51%,\r\n'
    '        rgba(240, 240, 240, 0.70) 100%);\r\n'
    '    border-color: rgba(0, 0, 0, 0.18);\r\n'
    '    box-shadow:\r\n'
    '      0 1px 3px rgba(0, 0, 0, 0.14),\r\n'
    '      inset 0 1px 0 rgba(255, 255, 255, 0.9);\r\n'
    '    color: var(--color-gray-700, #444);\r\n'
    '  }\r\n'
    '\r\n'
    '  // Active / pressed\r\n'
    '  &:active {\r\n'
    '    background: linear-gradient(to bottom,\r\n'
    '        rgba(170, 170, 170, 0.70) 0%,\r\n'
    '        rgba(195, 195, 195, 0.65) 100%);\r\n'
    '    border-color: rgba(0, 0, 0, 0.22);\r\n'
    '    box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.22);\r\n'
    '    color: var(--color-gray-700, #444);\r\n'
    '    transform: none;\r\n'
    '  }\r\n'
    '\r\n'
    '  // Active/toggled state \u2014 Aqua blue selection tint\r\n'
    '  &.active {\r\n'
    '    background: linear-gradient(to bottom,\r\n'
    '        rgba(88, 152, 228, 0.28) 0%,\r\n'
    '        rgba(60, 120, 210, 0.18) 100%);\r\n'
    '    border-color: rgba(88, 152, 228, 0.5);\r\n'
    '    box-shadow:\r\n'
    '      inset 0 1px 2px rgba(0, 0, 0, 0.10),\r\n'
    '      inset 0 0 0 1px rgba(88, 152, 228, 0.25);\r\n'
    '    color: #1254c0;\r\n'
    '    transform: none;\r\n'
    '  }\r\n'
    '\r\n'
    '  &.active:hover {\r\n'
    '    background: linear-gradient(to bottom,\r\n'
    '        rgba(110, 168, 238, 0.35) 0%,\r\n'
    '        rgba(78, 138, 220, 0.25) 100%);\r\n'
    '  }\r\n'
    '}'
)

new = (
    '.btn-icon {\r\n'
    '  width: 28px;\r\n'
    '  height: 28px;\r\n'
    '  border-radius: 50%; // Lion-style round toolbar button\r\n'
    '  // Gel gradient visible at rest \u2014 matches Lion round action buttons\r\n'
    '  background: linear-gradient(to bottom,\r\n'
    '      #f8f8f8 0%,\r\n'
    '      #e4e4e4 49%,\r\n'
    '      #d8d8d8 51%,\r\n'
    '      #f0f0f0 100%);\r\n'
    '  border: 1px solid rgba(0, 0, 0, 0.28);\r\n'
    '  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.8), 0 1px 2px rgba(0, 0, 0, 0.14);\r\n'
    '  color: #444444;\r\n'
    '  padding: 0;\r\n'
    '  display: flex;\r\n'
    '  justify-content: center;\r\n'
    '  align-items: center;\r\n'
    '  flex-shrink: 0;\r\n'
    '  cursor: pointer;\r\n'
    '  user-select: none;\r\n'
    '  overflow: hidden;\r\n'
    '  transition:\r\n'
    '    filter 0.1s,\r\n'
    '    box-shadow 0.1s;\r\n'
    '\r\n'
    '  // Remove the Aqua gel ::after shine \u2014 gradient is on the button itself\r\n'
    '  &::after {\r\n'
    '    display: none;\r\n'
    '  }\r\n'
    '\r\n'
    '  .material-icons {\r\n'
    '    font-size: 16px !important;\r\n'
    '  }\r\n'
    '\r\n'
    '  // Hover: brighten\r\n'
    '  &:hover {\r\n'
    '    filter: brightness(1.07);\r\n'
    '    box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.9), 0 1px 3px rgba(0, 0, 0, 0.22);\r\n'
    '  }\r\n'
    '\r\n'
    '  // Active / pressed\r\n'
    '  &:active {\r\n'
    '    filter: brightness(0.88);\r\n'
    '    box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.22);\r\n'
    '  }\r\n'
    '\r\n'
    '  // Active/toggled state \u2014 Aqua blue gel\r\n'
    '  &.active {\r\n'
    '    background: linear-gradient(to bottom,\r\n'
    '        #6eb8f8 0%,\r\n'
    '        #1e69de 49%,\r\n'
    '        #1050b4 51%,\r\n'
    '        #4a90e2 100%);\r\n'
    '    border-color: #1050a0;\r\n'
    '    box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.4), 0 1px 2px rgba(0, 0, 0, 0.3);\r\n'
    '    color: #ffffff;\r\n'
    '  }\r\n'
    '\r\n'
    '  &.active:hover {\r\n'
    '    filter: brightness(1.1);\r\n'
    '  }\r\n'
    '}'
)

if old in text:
    text = text.replace(old, new, 1)
    with open('design-system/themes/aqua/button.scss', 'wb') as f:
        f.write(text.encode('utf-8'))
    print('SUCCESS')
else:
    print('NOT FOUND')
    idx = text.find('.btn-icon {')
    print(repr(text[idx:idx+200]))
